#!/bin/bash

info="""
  ----------------------------------------------------

  Build your splines from file with points
  and find their intersection points or the
  distance between functions.

  Pass a file with points, where the number
  of points is indicated first, and then the points in
  XY a space-separated format.

  > create-spline input.txt

  Example, where two functions with 2 and 3 points respectively:

  2
  2 3
  4 5
  3
  1 1
  2 10
  3 -5

  ----------------------------------------------------
"""

echo "$info"

if [ ${#1} -eq 0 ]; then
  echo "create-spline: empty data!"
  exit
fi

path=$(readlink -f "$1")

python3 src/validator.py "$path"
if [ $? -eq 255 ]; then
  echo "create-spline: invalid data!"
  exit
fi

./spline "$path"
if [ $? -ne 0 ]; then
  echo "create-spline: fatal spline build!"
  exit
fi

graphics=$(ls | grep -P -o ".*\.spline")

python3 src/graph.py "$graphics"

for graphic in $graphics; do rm "$graphic"; done
